remove hardcoded string and use from lang file
onaio/reveal-frontend pull request #1553
Opened 2021-04-15 05:46 UTC by haseemVD

This PR addresses #1524

2021-04-15 09:05 UTC, ciremusyoka requested changes
This string should also be translated to Thai. Right?

2021-04-15 10:57 UTC, haseemVD commented
> This string should also be translated to Thai. Right?

Added comment on [issue](https://github.com/onaio/reveal-frontend/issues/1524#issuecomment-820270941), Will update PR after getting translation.

2021-04-22 09:08 UTC, ciremusyoka approved these changes

2021-04-22 11:30 UTC, moshthepitt approved these changes

2021-04-22 11:30 UTC, merged