Fix column text overflow
onaio/reveal-frontend pull request #1565
Opened 2021-04-23 07:56 UTC by ciremusyoka

Closes #1560 
![Screenshot from 2021-04-23 10-55-28](https://user-images.githubusercontent.com/26719807/115838519-7002b100-a422-11eb-91cb-49bb57b4734f.png)

2021-04-23 08:12 UTC, moshthepitt requested changes
1. Can we add a test?
2. Why not add a CSS class instead of making this change inline?

2021-04-23 09:59 UTC, moshthepitt approved these changes

2021-04-23 12:03 UTC, haseemVD approved these changes

2021-04-23 14:14 UTC, merged

2021-04-26 06:58 UTC, Naima-Bashir commented
This has passed QA